### ISSUE TITLE
Converting to EPUB: preserve original unicode instead of converting to HTML entity

### ISSUE THREAD

**Issue by elmimmo** [joseph/peregrin#9]
When converting to epub from an UTF-8 zhook, non-ASCII characters are converted to what I guess are hexadecimal HTML entities, like "Título" becomes `T&#xED;tulo`.

According to Joseph, it is apparently a Nokogiri issue, and may be transparently fixed with new versions.

>   Nokogiri is the tool that does the parsing in Peregrin — it's using libxml2 behind the scenes to transform the document.

These two links might be referring to the same issue (and offer a workaround?):
-   [Contents of a node in Nokogiri](http://stackoverflow.com/questions/2524305/contents-of-a-node-in-nokogiri)
-   Answer to [how can i make nokogiri just transparently return un/encoded html](http://twitter.com/#!/tenderlove/status/11489447561).

**Comment by joseph** [comment]
Should be addressed in 197ca3322727eac192f1205581fb026a5c6cc347. Please confirm and close if appropriate.

**Comment by elmimmo** [comment]
Please excuse me for being illiterate in version tracking and patching. How should I check?

I just installed peregrin on Mac OS X 10.6.6 this way:

```
$ git clone https://github.com/joseph/peregrin.git
$ rake package
$ gem install pkg/peregrin-1.1.0.gem
```

Then added `$HOME/.gem/ruby/1.8/bin` to my path.

Finally run

```
$ peregrin ochook ./book.epub
```

Non-ASCII characters are still being converted to entitites.

**Comment by elmimmo** [comment]
Peregrin Version: 1.1.1 leaves nasty hex entities behind. Yay!
